name: Check code style

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run check
      run: find . -type f -name '*.[ch]' -o -name '*.cpp' -o -name '*.hpp' | xargs clang-format --style=file:.clang-format -i --verbose

    - name: Compare result
      run: git diff --exit-code
